project_name: crog
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
  - maintainer: Henry Whitaker <henrywhitaker3@outlook.com>

    description: A CLI tool to setup scheduled tasks and call URLs based on the result, configured in yaml

    homepage: https://github.com/henrywhitaker3/crog

    license: MIT

    formats:
      - deb

    contents:
      - src: build/crog.service
        dst: /etc/systemd/system/crog.service

      - src: build/crog.yaml
        dst: /etc/crog/crog.yaml
        type: config

    scripts:
      preremove: build/preremove.sh
