version: '3'

tasks:
  build:linux:amd64:
    cmds:
      - task: build
        vars:
          OS: linux
          ARCH: amd64
      
  build:linux:arm64:
    cmds:
      - task: build
        vars:
          OS: linux
          ARCH: arm64
      
  build:linux:arm:
    cmds:
      - task: build
        vars:
          OS: linux
          ARCH: arm

  build:
    cmds:
      - GOOS={{ .OS }} GOARCH={{ .ARCH }} go build -o build/healthcheck_$(go run main.go --version | grep -Eo "[0-9]+\.[0-9]+\.[0-9]")_{{ .OS }}-{{ .ARCH }}